### ISSUE TITLE
Learning Product Design

### ISSUE THREAD

**Issue by bezierer** [designdetails/designdetails#100]
Long-time listener, first-time caller here 👋 

This is related to #46  – I've been doing UI/UX/Front End work in an agency setting for nearly 8 years, but curious about making the transition to Product Design. The roadblock for me is companies always want “x years of _Product_ experience”. Besides “go build a product”, what is some advice on learning the nuances of designing in a product setting? Are there books or courses that could help? I'm fairly well-paid and have a family so taking a Jr. level job to “get my foot in the door” isn't really an option for me right now.

Thanks, love the show!

**Comment by ngeshlew** [comment]
Hey Cameron 👋🏽, I wanted to attempt this question from my experience. Might still be useful. I gained more confidence once I went through this **playbook** during my journey on becoming a Product Designer. It's a collection of insights from some experienced Product Designers and it can help you (if the concern is still there) with getting the job. Here's the resource: [LINK HERE](https://askplaybook.com/collection/get-your-first-product-design-job)

![image](https://user-images.githubusercontent.com/4710827/104333565-7370cd00-5502-11eb-8fc5-b4115d9be070.png)

Hope it's useful. Have a great one! 🚀
