### ISSUE TITLE
How to find design teams abroad?

### ISSUE THREAD

**Issue by michadesign** [designdetails/designdetails#11]
Hey Design-Friends,

I was wondering whether you have any tips or ideas how to learn, connect and eventually apply with design-driven companies in other countries outside your home country. Aren't there great teams in South America, Asia or Africa?

I'm based in Germany and sometimes its even hard to tell what happens in neighboring countries like France, UK or Spain.

Where would you start your research? What would you recommend doing?

Best,
M

**Comment by arpitanand** [comment]
I'm a developer by profession, so I don't know how much this would help you. I'm based in India and the design culture here has really picked up in the past couple of years. 

I use [Muzli](https://muz.li) as my new-tab page. It aggregates design content from 100+ sources and puts it right in your browser's new-tab. Most of the content here is from really awesome designers and design agencies. I think that should help you discover interesting design teams and agencies across the globe.

As for connecting and applying, I think that process should work similar to how it works for the developer community. Churn out mini-projects and showcase them on all the relevant communities (for designers these should be Twitter, Instagram, Dribbble, etc.). Get feedback on your projects and try to incorporate them. Whenever possible, give out constructive feedback to you fellow designers. Once you become a part of that ecosystem, discovering potential opportunities becomes way easier.

I've been doing something similar in my local developer community, works great so far.
Hope this helps you too 😇
