### ISSUE TITLE
Email apps

### ISSUE THREAD

**Issue by 77Amy** [designdetails/designdetails#128]
Hi guys. 
Love your podcast. Really useful for me, I want to break into UI design. 
Hope this isn't a naive question - why are there so many email apps? Are they really that different from each other, and if so, how? What would prompt an average user to use a more obscure app instead of something like Outlook or the native email app on their device?
Thanks!

**Comment by brianlovin** [comment]
Not a naive question! I've wondered the same thing myself...could be fun to dig into.
