### ISSUE TITLE
One-Hand Myth on Mobile 📱

### ISSUE THREAD

**Issue by vinnie329** [designdetails/designdetails#484]
I would love to get both your takes on the one-hand myth that a lot of designers seem to buy-in to when designing for mobile. The myth suggests that all people use one hand to interact with their phones and so interfaces should be designed accordingly. This may have been true on the early smartphones which were smaller and where apps tended to be simpler. However, with devices getting bigger and heavier it seems like people use both hands for more complex, high-stakes tasks (buying something) and one hand for simple, low-stakes tasks (scrolling through a feed). Is this what you guys have found to be true? And is there any recent research around how people use their hands to interact with their phones? Mobile phone 

It would be super interesting to understand how you and Marshall think about this when designing for mobile!

**Comment by brianlovin** [comment]
Discussed in last week's episode! https://designdetails.fm/episodes/aUyTuSBj
