### ISSUE TITLE
'Future-proof' designer

### ISSUE THREAD

**Issue by loucaspapa** [designdetails/designdetails#486]
Design has matured as a discipline, there are a lot of good people in the industry, we've design systems, better processes, but it also becomes more commoditised. In what skills do you think an experienced designer should invest now to be 'Future-proof' in the next few years? For instance 3D and AR/VR are expected only to get more and more popular, AI and machine learning are already very much in demand, etc. What do you think? On what do you invest yourself in nowadays? 

Keep up the great job you're doing! You're my favourite podcast-company :)

**Comment by loucaspapa** [comment]
> Design has matured as a discipline, there are a lot of good people in the industry, we've design systems, better processes, but it also becomes more commoditised. In what skills do you think an experienced designer should invest now to be 'Future-proof' in the next few years? For instance 3D and AR/VR are expected only to get more and more popular, AI and machine learning are already very much in demand, etc. What do you think? On what do you invest yourself in nowadays?
> 
> Keep up the great job you're doing! You're my favourite podcast-company :)

Thanks a lot for answering my question in your last episode. I agree with you, design foundations, good communication and leadership skills and writing are the way to go to be 'Future-proof'. I'll make sure to cover some of them in my 2021 planning.

**Comment by brianlovin** [comment]
Hope it was helpful! Link for future browsers: https://designdetails.fm/episodes/h5VhO2W3
