### ISSUE TITLE
Lack of design empathy by developers  

### ISSUE THREAD

**Issue by thechanch** [designdetails/designdetails#498]
I need some advice, the work we are handing-off is being implemented in a sloppy way, with not a lot of design empathy or consideration of experience by the developers working on the product. The handoff process has become more and more detailed as we try to not lose the fidelity of the feature we’ve designed, but often certain decisions are made on the dev side where a choice is “good enough” and fails to adhere to the requirements of the design. Because of this, it goes through a (mainly dev) approval/PR process and when it comes time to test with more senior stakeholders, the designers get lambasted for delivering a subpar experience and when we defend ourselves mentioning that the implementation is not “as-designed”, we get called out for either not caring enough or not being more on top of them to work closer to the handoff docs while the developers remain coddled in a “did-no-wrong” attitude. I don't know if this may be related to unrealistic deadlines by dev leads or PMs but it is certainly possible that the root of this issue is just lack of bandwidth on their part.

i don’t know if its relevant but we don’t have a design leader/manager/stakeholder higher up at the company; we are 2 product designers and 1 UX designer currently hierarchically under the Director of Product. i’ve noticed that not having a more senior voice that speaks our language means our recommendations and criticisms of the process have fallen on deaf ears. What steps can we take to make sure that not only is the work done properly after handoff, but try to establish a more widespread culture about caring about the work everyone is doing?

**Comment by brianlovin** [comment]
Discussed on last week's episode! https://designdetails.fm/episodes/ssaB2TuT
