### ISSUE TITLE
Adaptive design for all screen sizes

### ISSUE THREAD

**Issue by erinm1** [designdetails/designdetails#500]
Hi Brian & Marshall,

I’m fairly new to the industry. I’ve taken my first job as the sole handler for the UX/UI design of an iOS app for a small startup. My background in design is self taught with help from an online course, prior to this I had never so much as even opened a design application. So I apologize in advance, my question I’m sure is very basic knowledge. 

My question is concerning adaptive design for different screen sizes. I’ve learned it’s best practice to design for the smallest screen size to ensure the UI does not break. However, my first feature was launched this week and I was very disappointed to see how my designs appeared on my larger device (iphoneXr). The components scaled fine, the text size however, wasn’t quite legible.

Do you have advice you can lend on how I can ensure my designs are consistent on across all screen sizes? & how do you recommend conveying this to my development team?

**Comment by brianlovin** [comment]
Discussed in last week's Sidebar! https://designdetails.fm/episodes/ssaB2TuT
