### ISSUE TITLE
Purposefully hard to find features

### ISSUE THREAD

**Issue by matt50641** [designdetails/designdetails#503]
Hi, I’m wondering if you have any thoughts on making certain features of a website more difficult to find. For example, if I want to talk or chat with an actual human about an Amazon order, one has to find Customer Service in the app, then step through multiple selection screens to narrow down the topic, issue, specific item, read though the “standard” answers, pick “I need more help”, select a communication preference, confirm multiple times that you want to start a chat.....you get the picture. I assume this does cut down the number of live interactions they need to handle, but if I know for sure I want to talk to someone, the process can be annoying when presumably the buyer is already upset about an issue. Thanks!!

**Comment by brianlovin** [comment]
I think these are all dark patterns. Companies save money on support by offering more self-serve support. If the tooling there like docs, FAQ, or community spaces can help people self-serve answers to their questions, it does seem like a win overall. But I 100% agree, it's entirely frustrating to have to dig through menu after menu to get a phone number or a contact email.
