### ISSUE TITLE
Should I pursue Product Design or Development?

### ISSUE THREAD

**Issue by dluft** [designdetails/designdetails#506]
Hey Brian and Marshall,

I’m a Graphic Designer who wants to grow in his career. I want to change my job to either Product Design or Development (unsure if front or back end.) How should I decide which path to go down? 

Questions which make me hesitate:

* As a Product Designer, is it uncomfortable that Developers earn a higher salary?

* Can a Product Designer be taken seriously as a founder? 

* Do Founding Designers receive fair equity in startups?

* Is it hard to go from being a Product Designer to being a Developer (and vice versa?)

* Is Product Design a satisfying career?

Thank you for reading and answering my questions.

Extra info:

* I’m 25 and live in NYC.

* I have redesigned a couple of websites and designed landing pages at work.

* I have been learning HTML, CSS and JavaScript through online courses at SuperHi.

* I have a BFA in illustration. I pivoted into graphic design because I took classes in it at the end of college and had enough work to get a job.

* I have not yet tried a traditional “Design Thinking” UX project.

**Comment by brianlovin** [comment]
Discussed in https://designdetails.fm/episodes/w0BtPjE6 😊

**Comment by dluft** [comment]
Hey Brian! I deeply appreciate the advice you and Marshall gave me in that episode.

You're right, I haven't yet figured out what I like. I will spend more time exploring what feels right for me and update you here on my journey. I won't let you guys down!

Thank you for addressing all of my questions!

By the way, I would enjoy hearing you guys go deeper into the career path/responsibilities of UX Engineers. What is that role all about? How do you become one?

**Comment by brianlovin** [comment]
> By the way, I would enjoy hearing you guys go deeper into the career path/responsibilities of UX Engineers. What is that role all about? How do you become one?

Good questions! Maybe we can interview a UX or UI Engineer specifically, thanks for the idea 😊
