### ISSUE TITLE
Transcript update for episode 372

### ISSUE THREAD

**Issue by pwongerz** [designdetails/designdetails#509]
Did some edits throughout the entire episode

**Comment by brianlovin** [comment]
Hey 😊 Would be you up for opening this as a pull request with the edits? Let me know if I can help out with anything

**Comment by pwongerz** [comment]
Hey Brian,

Sorry I'm still trying to figure out how to do a pull request! I realized
someone else updated it a few days ago which is better than mine so I'll
just wait for your next episode :)

Thanks,
Priscilla

**Comment by brianlovin** [comment]
Sounds good! https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request might be a good place to start, too 😊
