### ISSUE TITLE
Is Apple era going to be over eventually?

### ISSUE THREAD

**Issue by tamara2153** [designdetails/designdetails#510]
At the risk of starting a holy war... 
I was listening to the most recent Sidebar (#373 discussing new Apple computers) and heard Brian and Marshall complain about their computers =) If I'm not mistaken, Marshall has fans pointed at his laptop to prevent overheating, and Brian struggles to keep the computer running with two displays connected. 
I started my career working on PCs. My husband (who's a mechanical engineer) still uses Windows and despises Macs for their price, lack of flexibility, and some design decisions. So in our household, we have this conversation rather frequently – are Macs worth it? In my personal experience, way back when I did a lot of high-end photo retouching, our home PC tower that my husband put together back in 2014 was outperforming the top MacPro tower (aka Trashcan) I had at work. 
In Design, Mac computers are the de-facto standard, and I personally love these machines' industrial design. However, with modern design tools evolving past the Apple environment (Figma, XD), the Apple ecosystem being ever so exclusive, and PC manufacturers stepping up their design game, every time I am faced with the choice of a new computer I wonder if I should get a PC. 
Of course, there are many more factors than just pure performance that contribute to the success of Apple computers. 
I wonder if either of you has ever considered the PC as a working computer, and why? 

Thank you for a great show!

**Comment by brianlovin** [comment]
Discussed in https://designdetails.fm/episodes/ySHKMjxV 😊
