### ISSUE TITLE
How to start an interview podcast?

### ISSUE THREAD

**Issue by yOoMarvin** [designdetails/designdetails#514]
Hey, guys, 
as a long time listener and huge podcast fan, I have tried to hang a toe in the water myself. For 1 year I did a solo podcast, then I quit. Now the desire to get back into the business is growing. But this time with an interview podcast. My question to the experts: What is the best way to get in? How do you find the right people? And how do you conduct an exciting interview? Do you have a fixed structure? Or is it more like a muscle that you have to train?

I would be very happy about a little help to get started!

Greetings from Germany!
And stay healthy!

**Comment by brianlovin** [comment]
Discussed in The Sidebar of today's episode! https://designdetails.fm/episodes/u6kUMiqA

**Comment by yOoMarvin** [comment]
Thank you guys so much! It was super helpful to hear your thoughts on the topic. I will definitely use this as a guide when starting out with the new podcast 🚀 I'm super motivated right now 💪 And of course, I'll let you know how it's going 😉

**Comment by brianlovin** [comment]
Hit us up with a link when you restart 😊
