### ISSUE TITLE
How do you record and edit your podcast?

### ISSUE THREAD

**Issue by JorneMarc** [designdetails/designdetails#516]
Hey there,
I would love to know how you approach producing your podcast? I have the feeling that you talked about it some time ago, but I can’t - or am too lazy - to find out in which episode you talked about it.
Either way: What’s your workflow? What kind of software do you use? Do you use any DAW plugins you can recommend? What kind of gear do you use? How do you prepare?
If you found the episode: Can you tell me which one it is? And did something change from your workflow back then?

Cheers!

**Comment by JorneMarc** [comment]
I opened this issue right before I listened to the **Sidebar of Episode 375**.
For everyone interested in Bryn’s Blog Posts _Podcasting: The Basics_:
[https://medium.com/@superbryntendo/podcasting-the-basics-b4936ece1d06](Podcasting: The Basics, 2015)
[https://medium.com/@superbryntendo/podcasting-the-basics-v2-32bd2778a8db](Podcasting: The Basics (v2), 2018)

So the only question left would be:
What changed and why?

**Comment by brianlovin** [comment]
Ay, hopefully 375 helped! I think Bryn re-wrote the post after he had more experience and information, I'm not sure about the exact delta between the content 😊
