### ISSUE TITLE
Design philosophies and reality

### ISSUE THREAD

**Issue by katarinablind** [designdetails/designdetails#517]
Design philosophies are great. They can help express complex thoughts and visions to solve problems. However, I think that sometimes they drift off from the real life and the impact a product actually has/ can have. 
How do you think this idealistic mindset can be brought closer to reality (especially talking about companies since personal project tend to have less impact/ connection to actual life... also an interesting aspect btw)?

**Comment by brianlovin** [comment]
Interesting question, do you have an example by chance to demonstrate what you mean?

**Comment by katarinablind** [comment]
TikTok and similar services in other products provide high volumes of fast entertainment. A philosophy that isn’t really touch with reality would then be “giving all unique and modern creatives a platform to use their voice to impact other peoples lives and inspire them to come together and be empowered to share their culture”. This is over the top phrasing of course but might help to get a better idea.
