### ISSUE TITLE
Who should handle UI Reviews: Designers or QA?

### ISSUE THREAD

**Issue by PriscillaThen** [designdetails/designdetails#518]
Should designers perform UI reviews after dev implementation, or should QA be responsible for that? 
I think that it's the job for designers, since we're the ones that created the mocks, and have the sensitivity to the finer details (typography, spacing, alignment, etc.) but the Product Manager thinks that UI reviews should be done by a QA. I'd like to hear how other companies handle it!

**Comment by brianlovin** [comment]
Discussed yesterday, too! https://designdetails.fm/episodes/6dZ429dD
