### ISSUE TITLE
Having a portfolio versus having an opinion

### ISSUE THREAD

**Issue by kemiljk** [designdetails/designdetails#522]
Feel free to say my name Karl etc. Holla y'all.

Long time follow up from May when a [tweet](https://twitter.com/rowancba/status/1263165291288162305?s=21) about me interviewing with someone who also listened was mentioned but my name was of course spared. It didn't work out. But, he almost came and worked with me at my new place but decided to follow his passion in the end. We almost had a Design Details work marriage. So close! 

Anyway... I just had a shower thought and wanted to share. Where do you both land on the idea of having a web presence that is focused on showcasing your opinion versus showcasing your work. 

More and more it feels like having an online opinion about the state of our industry and practice versus just showing some nice UX or UI portfolio is becoming increasingly important to stand out. I know Brian's site is much more about having a presence (and I know that's a big goal of his) so I'm just curious on your takes.

**Comment by brianlovin** [comment]
Discussed in today's Sidebar! https://designdetails.fm/episodes/odJXcIY7
