### ISSUE TITLE
I want to launch a personal project *for real*, what do I need to consider?

### ISSUE THREAD

**Issue by mknepprath** [designdetails/designdetails#525]
I have [an app](http://lilydex.com/) I want to launch - so far I've tweeted about it and shared it with friends. But I think it's cool and potentially useful to lots of people! Do you have a checklist you run through when launching new products or features?

I was going to suggest getting Super Bryntendo on as a guest to answer this due to y'alls experience launching Spectrum. Then he tweeted this... https://twitter.com/superbryntendo/status/1339665880532144128

So now you have to.

Thanks!

**Comment by mknepprath** [comment]
Also, is Product Hunt as important as it used to be for this?

**Comment by brianlovin** [comment]
Discussed today! https://designdetails.fm/episodes/odJXcIY7 → Let me know if this was useful at all @mknepprath 😊
