### ISSUE TITLE
Yearly! Am I early to ask this?

### ISSUE THREAD

**Issue by antzfx** [designdetails/designdetails#529]
Hi Brian and Marshall,
I just set up a Patreon account to become a Pixel.
Realised that only monthly options are there to support DesignDetails.
Is it possible to add a $12 Annual Subscription in Patreon?

Why, you ask? I'm from India. My currency is 'Indian Rupees' (INR) and the bank charges a conversion fee to USD/GBP/CAD/EUR. That is not a good thing as currency rates fluctuate everyday and there is less predictability on the monthly amount. 

Could you please consider my request? So that I can pay now and forget renewal for a year :)

**Comment by brianlovin** [comment]
Great question! Patreon does support a yearly payment option, however I'm hesitant to set the expectation for all new subs that they should expect the same benefits for a full year. We have iterated on the benefits for patrons over the months, so I want to make sure people's expectations are met and they aren't disappointed if we change things. 

How does this feel for you?

**Comment by antzfx** [comment]
Thank you Brian for the reply.

I didn't quite understand the reason for keeping it monthly, but I respect your decision. You must be doing it right.

Incidentally, Armin of UnderConsideration/BrandNew introduced subscription model in 2020 to survive and his posts on subscription updates restored my faith in humanity.
One sample update: https://www.underconsideration.com/brandnew/archives/subscription_model_progress_and_update.php

Take care and stay safe!
