### ISSUE TITLE
Your thoughts on designing for phygital and omni channel experiences?

### ISSUE THREAD

**Issue by flyingjuggernaut** [designdetails/designdetails#532]
Digital platforms are there to enhance our activities in the physical world.
But more often than not, we UX designers think about the user journey as it starts and ends in the digital world. 
Users, on the other hand, don't necessarily differentiate between digital and physical and think of a company as one channel.
This causes a lot of issues that impact the health of humans or affect the environment in a bad way.
Any thoughts on how to design for these phygital and omnichannel experiences? Which companies do you think do it the best? 

- Jatin

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/sWUOkJPS

**Comment by flyingjuggernaut** [comment]
Just listened to the episode and thanks for picking it up. Overall a great take. 

When I say the impact on the health of humans, I am thinking about Netflix or Youtube promoting binge-watching which leaves people sleep-deprived, or the endless scroll in social media apps causing people anxiety, depression, and ADHD.

For environmental impact, one example that comes to mind is Amazon not recognizing orders placed minutes apart by a user and sending them in separate packages.

Hope this helps.
