### ISSUE TITLE
Finding time for future product exploration

### ISSUE THREAD

**Issue by jcafazza** [designdetails/designdetails#538]
Hey guys, first time writer, long time listener.

Question: With a typical day being filled with heads down work, review sessions, and all the things necessary for shipping new features, how do you and your larger design team find the time and headspace to design for the future of your product? A proverbial North Star vision for the entire Product.

The company I work at (Amex) has historically leveraged external agencies to help do this, but this comes with its pluses and minuses.

Curious if you guys have any thoughts or insights.

Cheers!

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/wszp8IIz
