### ISSUE TITLE
What does it take to transition from web to native?

### ISSUE THREAD

**Issue by jasonlockwood** [designdetails/designdetails#539]
Having spent 10 years designing and coding websites and web apps, I am looking to broaden my skill set by transitioning to native (iOS, Android) in my next role. As I look over job posts, many require experience designing for iOS or Android. What are some of your thoughts or tips for someone who has senior experience looking to dip their toes into native for the first time?

PS - Thank you so much for your contribution to the design community. Keep on killin' it!

**Comment by brianlovin** [comment]
Discussed in last week's episode! https://designdetails.fm/episodes/5_5TJCU3

**Comment by jasonlockwood** [comment]
Thanks for including this as a sidebar discussion. I found the discussion really helpful for what considerations to make, and areas for study & practice when starting out. 

One thing I am curious about is the differences between web & native when it comes to working with engineers and engineering literacy.

I've built a pretty great understanding of frontend web developement and I am very comfortable communicating with engineers who are working with HTML, CSS, and JS frameworks. However, native languages like Swift, Objective-C, Kotlin, Java, etc. are a whole new world to me. Would you recommend investing some time in learning the fundamentals of major native languages to build better literacy?
