### ISSUE TITLE
Man offers Newport council £50m if it helps find bitcoins in landfill

### ISSUE THREAD

**Issue by loucaspapa** [designdetails/designdetails#541]
I listened in one of your last episodes about a person that had forgotten his password to access his bitcoin folio, and thought you should check this story as well : [Man offers Newport council £50m if it helps find bitcoins in landfill](https://www.theguardian.com/uk-news/2021/jan/14/man-newport-council-50m-helps-find-bitcoins-landfill-james-howells)

**Comment by brianlovin** [comment]
Amazing. This has to be among the worst pit-in-your-stomach feelings in the world 😛
