### ISSUE TITLE
What to do when the design team’s bar for UI is low?

### ISSUE THREAD

**Issue by sallythat** [designdetails/designdetails#543]
I am a few months into a new company and most of the designers are content to ship work that wouldn’t pass design reviews at my previous company. I know we aren’t being lazy; we invest in research and making sure we’re solving problems. But the UI is poor and both stakeholders and customers have complained about it.

We do have a design system and the company is working on a new one. But I’ve been disappointed with the design system team’s output.

It often feels like we lack the desire or competency to address the UI gap. And I’m losing motivation because I’ve worked with teams who inspire and push each other to improve our craft.

I’ve tried to address the gap by setting up regular design reviews. But I’m an IC and I don’t want to over reach or burn out by worrying about other people’s work.

I don’t know how to raise this to my manager because I do not want to come across as being egotistical. Are my expectations unrealistic or perhaps I made the wrong move and should leave for company with a higher bar for design quality?

PS - Love the podcast. I'm a regular listener :)

**Comment by brianlovin** [comment]
Discussed in last week's episode! https://designdetails.fm/episodes/5_5TJCU3
