### ISSUE TITLE
Designing with grid systems?

### ISSUE THREAD

**Issue by joeyjungle** [designdetails/designdetails#546]
Hi!

So I've seen a ton of articles about using grids in design and using an 8px grid system as a baseline for spacing, but I don't really understand the mechanics of setting that up in practice - particularly for mobile. Because none of the iPhone devices are evenly divisible by 4/8/12px, it doesn't seem like there's a great way of setting up a square grid for your design? 

It seems like there should be a way of setting up a device frame with a four column grid, and then nesting a component frame inside of that device frame, with the component frame using a square 8px grid that neatly flows across the full width of 2 or 4 columns, with every 8th pixel from the square grid landing perfectly on the edges of the columns and no fractions of squares spilling over into the gutters or margins.

Am I missing something about setting up grids, or am I trying to use them in a way that isn't really possible? 

If there's no way of preventing spillover, how do you use an 8pt grid to represent padding on all 4 sides of a component frame, when the righthand side of the component frame might have something like 6/8ths of a grid block aligned inside the device frame columns and 2/8ths spilling over into a gutter or margin?

If I have anything conceptually wrong about an 8pt grid system, please correct my misunderstanding!

Thank you so much!

**Comment by branhillsdesign** [comment]
Personally I use a 320px wide grid for mobile and design within that. The margins on the outside of that grid are fluid. This way the 8px grid works within the boundaries that you need. 

Here's a [post](https://spec.fm/specifics/8-pt-grid) about the 8-point grid direct from spec.fm that outlines best practices.

**Comment by joeyjungle** [comment]
@branhillsdesign You just blew my mind 🤯 I've literally never thought about not using the preset frame/artboard sizes. So you're basically using frames as a container size and don't even need margins on the actual frame you're working in?

**Comment by branhillsdesign** [comment]
Absolutely. 

I work in XD, but here's an [image](https://user-images.githubusercontent.com/51428934/108738081-d89fe100-74f8-11eb-9738-9a10571132b8.png) of how I use the grid and guides for mobile.  Grid is just laid on the artboard at 8x8, you'll notice the last grid column on the right side isn't quite 8px, but my content stays within my 328px guidelines in light blue. You can do something similar in Figma as well.

**Comment by haenschenhans** [comment]
that's a great question and I would also be curious how other teams are handling this

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/hgPwR4Ey
