### ISSUE TITLE
How to give specific feedback when you’re not in that same problem space extensively 

### ISSUE THREAD

**Issue by skrapkam** [designdetails/designdetails#550]
Hey guys,

A problem that I've been encountering in my product team is how to give specific feedback when you’re not in that same problem space extensively. We recently began to give designers ownership over specific areas of the product e.g. I'm working on the funnel experience, another designer is working on the partnership space, etc. 

The problem is that it can be hard for me to give specific and detailed feedback in a design crit, for example, on partnership related things that my fellow designer is working on. Since I'm not spending as much time and energy in that problem space, I feel like most of my feedback is quite shallow. Curious to hear if you guys encountered this issue before or have any potential solutions to this problem.

Thanks!

**Comment by skrapkam** [comment]
Thanks for the great ideas y'all! Super helpful.

**Comment by brianlovin** [comment]
Hope it's helpful! Link for this discussion: https://designdetails.fm/episodes/S9I_Q2jR
