### ISSUE TITLE
How do you all organize and consume articles, case studies, etc. and then how do you action the information?

### ISSUE THREAD

**Issue by AdamWpg** [designdetails/designdetails#557]
As someone who as relatively new to product design, I am always looking for new tips and insights. I'm subscribed to a few newsletters and frequent some blogs that I've really enjoyed, but the problem is that it's not always possible to take the time to really absorb the information at that moment. So I end up trying to save the articles, but I don't really have a great system. I've tried Pocket, but I wasn't crazy about it. For a little while I used Google Keep and that works fairly well, but I sort of fell off of that, and now I basically have a rolling browser window with anywhere from 10-50 tabs waiting for my attention at any given moment. And then when I do read the content, if it's not something I can immediately apply to what I'm working on, how do I remember what I've learned so I can apply it later?

I'd love to know if this is something you've worked out a system for.

**Comment by AdamWpg** [comment]
@brianlovin thanks so much for the thoughtful response from both of you on the podcast. I actually love that you guys sort of challenged the premise of my question. This really made me think deeply about what I'm actually trying to do by reading all of these articles. I think part of it is that I just find it really interesting to learn different perspectives about design because I love this line of work and I'm really excited about it. The other part is something that Marshall touched on - he said that a lot of the things he sees are either refreshers or things that he knows deep in his bones, and that's where I want to get to but I'm not there yet. I love to learn and soak up as much as I can and I feel like it gives me a level of confidence to have a little context and knowledge around areas that maybe I haven't spent much time on yet. 

Deep down I knew that I would probably never go back to anything I've saved - I just needed to hear someone say it. The purpose of switching to having tabs open was meant to make me clear them out faster because they would constantly be in my face, but they just sat there.

Going forward, my policy will be that if I see something that looks interesting and I don't take the time to read it by the end of the day, it's not getting saved. I still want to consume this kind of content because I enjoy it, and in order to keep enjoying it, it can't be looming over me. So you'll be happy to know I have closed my browser window of doom. I'm not going to focus on wanting to remember everything I read - I think I can be satisfied to enjoy the content and let the ideas just float around somewhere in my subconscious.

Thank you for what you guys do. I can honestly say that Design Details was a critical element in really igniting my love for design. I really don't think I would be a designer right now if it wasn't for the show.

**Comment by brianlovin** [comment]
❤️  thank you so much for saying that Adam! It was a fun topic, and we both resonated with the feeling a lot – I think ultimately you just gotta find what works best for you, it seems like everyone has a slightly different appetite for reading things through the day.

Good luck 😊 

Episode link for future browsers: https://designdetails.fm/episodes/rKjF2y1A
