### ISSUE TITLE
Thoughts on dark mode

### ISSUE THREAD

**Issue by danashelton** [designdetails/designdetails#56]
Hi guys, love the show I am a regular listener on my way into work and I think you guys are great! So thanks for all you do and please keep it up for those poor people like me who aren't immersed in the San Fran or NY epicenters of the world. 😍

I am a UX Designer in healthcare at a startup in Cleveland, Oh and I just finished a remote patient monitoring system so Anesthesiologists and other Critical Care providers can keep an eye on their patients even away from the bedside. It's pretty cool and what makes it even more unique in this vertical is that I did it in dark mode before there was really a lot of guidance out on how to implement this type of design. I bucked a few recommendations by having that freedom but the major one I want to point out is the elevation strategy. 

Ready for this? What if you're looking down instead of up? I used a dark slate blue grey background and each stacked layer gets darker instead of lighter. 🤯

My point is as long as there is a progression logically in either direction, the design works. Honestly, I would venture to guess my way works to reduce power to more pixels since the primary focus is always the darkest layer and the largest group of pixels, but that's not yet tested so just my hypothesis for now. No disrespect to Google, there is just more than one way to skin an app and that's mine. 

Thanks for reading guys, keep up the great work!

-Dana Shelton

**Comment by brianlovin** [comment]
Dana - really interesting approach. Would you be able to share screenshots as examples?
