### ISSUE TITLE
Strategy skills

### ISSUE THREAD

**Issue by jmtong** [designdetails/designdetails#563]
Hi Design Details team, 

I work at a small startup with less than 15 people and I'm the only designer. Recently, I've had a performance review and my manager, who is the Head of Product has recognised that I am lacking in "strategy skills". I seem to mostly come up with short term ideas. eg. we have a problem regarding X, so i am able to come up with multiple solutions, etc. I've also been to a job interview where they said I was lacking high level, strategy skills. I am unsure as to how to develop this skill and think of my work more in the long term and plan for the long term. My manager has suggested a book called "Good Strategy/Bad Strategy" by Richard Rumelt but other than that, he does not know how to help - probably because he is from a product management background, and I should be developing a UX strategy skills. Do you have any advice, or resources you can point me to where I can grow in this area as a product designer?

Thanks in advance.

Kind regards, 
Jessica.

**Comment by brianlovin** [comment]
Discussed last week! https://designdetails.fm/episodes/_Sj6tdNu
