### ISSUE TITLE
Deciding to build what the user wants vs. what you want to build for the user

### ISSUE THREAD

**Issue by victorkernes** [designdetails/designdetails#573]
Hey Brian and Marshall. 👋

Curious to hear both of your thoughts on the decision making process of building features that you’re users explicitly ask for (i.e. edit button on Twitter) versus features that your team, whether it’s Design, Product, Engineering, feels are the right things to build based on the company’s priorities.

User research plays a large part, however, it’s something I’ve been struggling with lately. Especially as I’m working on new features that the company’s prioritizing, which is another process I’ve been removed from so far.

Have a great day, y’all!

Victor

**Comment by brianlovin** [comment]
Discussed in today's episode https://designdetails.fm/episodes/KlnQ3m2x – thanks for the question @victorkernes 😊
