### ISSUE TITLE
How to develop "strong opinion weakly held" for visual design critique?

### ISSUE THREAD

**Issue by Yu-Alexa-Zhao** [designdetails/designdetails#575]
This question can be broken down to 3 parts:
* Is there such thing as "strong opinion weakly held" for visual design?
* How to develop strong opinion for visual design?
* How to present visual opinion to others without seeming arbitrary?

When I give or receive feedback on the visual design, smetimes I myself or other designers will use phrases such as "I feel like ...", "It is looking a little weird" - phraes that don't even convince me that they are strong opinions! Other times, I see people (myself included) making arbitary visual suggestions or even decisions that feel very "opinions strongly held". 

I wonder how to develop "strong opinion weakly held" for visual design critique?

**Comment by brianlovin** [comment]
Discussed in last week's episode! https://designdetails.fm/episodes/Dzc4_boh

**Comment by Yu-Alexa-Zhao** [comment]
Loved this episode! 

This episode got me thinking - is there any material difference between visual vs. interaction vs. product design decisions when it comes to adopting the "strong opinions weakly held"? It looks like the process of "forming a hypothesis and evaluating it with data" is same across different types of decisions.  

I also realized there might be some "UX maturity" pre-requisites to adopt a "strong opinion weakly held" mindset in design. For instance, the team needs to know how to use data to evaluate decisions (as opposed to use someone else's opinions to "evalute" your own opinion, for instance). 

It is also very interesting that both of you thought about design system when answering this question - something that never came across my mind! I work as a startup, and I am building out the components and documentation around them alongside each project. So there are a lot of juggling visual design decisions (while building the design system) and product design decisions (while working on the projects) at the same time. 

Yu
