### ISSUE TITLE
What is a 'Design Advisor'

### ISSUE THREAD

**Issue by mars1980** [designdetails/designdetails#578]
Hey ya'll! I've been seeing more and more folks who are 'Design Advisors' for Startups. Brian, I know you do this for Polywork. I want to know, what does this mean? How is it different than a design founder early on at a startup? How do you get in as a "design advisor" vs. just being the first hire at a startup? Ty!

**Comment by brianlovin** [comment]
Discussed in this week's Sidebar for episode 402!
