### ISSUE TITLE
Feature Request: Episode release date

### ISSUE THREAD

**Issue by yungbeto** [designdetails/designdetails#583]
Hello!

I was listening to a few older episodes from a couple years ago on designdetails.fm and couldn't find any info on when an episode was released (Or, I could just be a doofus and the release date **is** listed but I missed it 😅). Is there a way to expose that kind of info? 

Since the design landscape changes so quickly I think it could be helpful knowing when a conversation took place for better context (especially from several years ago). 

Thanks so much, I really enjoy your show!

**Comment by brianlovin** [comment]
Good call, I'll try to add this soon!
