### ISSUE TITLE
Who leads the UI design itself?

### ISSUE THREAD

**Issue by itaydre** [designdetails/designdetails#586]
It's been challenging to develop a new design system without an existing visual style guide, so I'm trying to explore more about the work behind designing UI when you're not a sole designer.

I've got a feeling that designing UI is quite hard to do collaboratively, as taste is very much subjective to each and every individual.

- What's your experience when it comes to developing a new style guide?
- Does a single designer lead the process (in terms of the visual direction)?

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/jq2bJ5cK
