### ISSUE TITLE
Big tech advice

### ISSUE THREAD

**Issue by BobbyDesigner** [designdetails/designdetails#587]
Hey, love the show! I have a question I'm not sure has been answered before:

I'm going to be starting as a designer at a big tech company soon, and I wanted to know if you guys had any advice on what to expect, how to succeed, tips & tricks of working in this environment. I am coming from a word of smaller startups.

**Comment by brianlovin** [comment]
We discussed this question in The Sidebar this week (on [Patreon](https://patreon.com/designdetails)): https://designdetails.fm/episodes/jq2bJ5cK

**Comment by BobbyDesigner** [comment]
Amazing thanks both, really great advice! (listening now!)
