### ISSUE TITLE
Change Lab & Design Details Podcast cross-promo?

### ISSUE THREAD

**Issue by mkpodglomerate** [designdetails/designdetails#604]
Hi,

Never before have I submitted a pitch via GitHub. I guess you learn something new every day?

I’d like to tell you about the new season of [Change Lab](https://docs.google.com/document/d/1WiYee_qlQwx5zhv2oPOPVag0l2kQjDnu1oE-AItH0j4/edit?usp=sharing), a longform interview podcast that explores the transformative power of creativity. Host Lorne M. Buchman, president of the ArtCenter College of design, interviews luminaries including author Aimee Bender, visual artist Ann Hamilton, Whirlpool design chief Tisha Johnson, Linkin Park performer and illustrator Mike Shinoda, and pioneering installation artist Diana Thater. Would you be interested in swapping cross-promos?

Through years of conversation with artists, designers, writers, musicians, and filmmakers, Lorne has developed a cohesive theory mapping the connections between the act of making and creative inspiration itself. As Lorne discusses in his forthcoming book [Make to Know](https://www.thamesandhudsonusa.com/books/make-to-know-from-spaces-of-uncertainty-to-creative-discovery-hardcover), creativity isn’t a matter of instant enlightenment. Rather, it’s a process of venturing into uncertain terrain,“carving” and refining ideas on the path to discovering what it is you’re making and how you want to make it.

If you’d like to hear early audio of Change Lab or take a look at the manuscript of Make to Know, please let me know. I promise the new season is worth a listen.

Best,

-Matt

**Comment by brianlovin** [comment]
Hey Matt, thanks for opening the issue here and for the idea – right now I'm not sure this is the best fit for a cross promo 😊
