### ISSUE TITLE
FUI (Fictional User Interfaces) and Future UI

### ISSUE THREAD

**Issue by sellty** [designdetails/designdetails#608]
I was a huge fan of Iron Man Jarvis style FUI's but after studying UI/UX at university, I can't help but notice how useless and not user-friendly some of the FUI's look. It's basically ruined me for any Marvel movies. However, I have been told that FUI should be seen inspiration to what our future user interfaces (or no-interface) will look and feel like. I'm curious to know what FUI you thought was really cool that you could see being used in a real world application in the future

**Comment by brianlovin** [comment]
Discussed in today's episode — thanks for asking about this, it was a really fun topic! https://designdetails.fm/episodes/BlIhI8Mi
