### ISSUE TITLE
Small vs. big level impact of features

### ISSUE THREAD

**Issue by katarinablind** [designdetails/designdetails#609]
How does one outweigh impact on a small vs. large scale? A feature might have different impact in a single moment than in the grand scheme of a large user base for a longer period of time.
These can conflict each other (maybe even accompanied by different types of goals).

For example infinite scroll on a small level helps to create a more seamless experience. The user can focus on the content instead of being reminded of extra layers (by manually viewing the next page).
However, on a larger scale this feature has wasted thousands of human hours. When there is no reminder to check in, people can get lost and just keep scrolling.

Is there any way how designers can deal with this issue in general? I’m curious to hear your thoughts.

**Comment by brianlovin** [comment]
We discussed this in the Sidebar of episode 420: https://designdetails.fm/episodes/koqM2mms (available to our [Patreon subscribers](https://patreon.com/designdetails))
