### ISSUE TITLE
Preparing for design challenges

### ISSUE THREAD

**Issue by thuy-luong** [designdetails/designdetails#611]
## Issue background
As a new designer going through the interview process, I want to be prepared to tackle design challenges. But with my lack of on-the-job design experiences, it's difficult for me to structure my approach.

## Current resources
YouTube videos, blog posts, and the book "Solving Product Design Exercises" by Artiom Dashinsky are the resources I've gathered to handle my current situation. I also know [ADPlist](adplist.org) has mentors that are open to mock challenges.

I have found numerous resources available to engineers for in-depth mock interviews and exercises, but not the same for design. I would imagine designers at all levels would benefit from keeping these skills polished.

## The big question
How do designers prepare for these challenges? Are there resources that I've just overlooked?

**Comment by brianlovin** [comment]
Discussed in this week's Sidebar: https://designdetails.fm/episodes/dSCbtu24
