### ISSUE TITLE
Regarding session recording tools for analytics

### ISSUE THREAD

**Issue by mukul23** [designdetails/designdetails#613]
Hi Brian & Marshall, my name is Mukul and I am from India. I enjoy listening to your episodes and the discussions are very insightful. One question I had is, other than the quantitative analytics tools like Google Analytics, Fathom etc do you use any qualitative i.e. user session recording tools like Hotjar/Smartlook,/FullStory etc? If so, can you please share your thoughts on these tools and how you use it/if you find it useful?  Would love to know how Github and Youtube on such a large scale do it. Also any opinion on which is the best tool according to you? Looking for a tool which works on both website and mobile app.

**Comment by brianlovin** [comment]
Hey @mukul23 — nothing comes to mind for me, sorry! At GitHub at least, we do usability tests with people and will use whatever tool we need for the fidelity of feedback we're looking for. 99% of the time that's a Figma prototype, or if we're a bit further ahead in development we can get people onto an Android/iOS beta. I'm not super familiar with some of those other tools though, sorry 😊

**Comment by mukul23** [comment]
No problem Brian :)
