### ISSUE TITLE
TestFlight usability testing

### ISSUE THREAD

**Issue by RazanSon** [designdetails/designdetails#615]
Morning I'm Razan from Saudi Arabia, I was very lucky when I found your podcast!

My question is, our team is planning to test a beta version from our app. I want to conduct unmoderated usability test with users since the app will show a sensitive data for the users. how can I get insights from the users using TestFlight Public Link like (misclicks, time on task, confusion rate, ...etc)?

Thank you!

**Comment by brianlovin** [comment]
Hey @RazanSon — I'm not actually sure how much of this is possible directly through TestFlight, as far as I know they don't have a lot of tools specifically designed for usability testing. You might need to do more custom integration of event tracking to learn some of these things, or you could do some research on iOS tools/frameworks for measuring things like session time or recording user flows. I'm not familiar with anything in this space though 😊
