### ISSUE TITLE
Share Frustrations

### ISSUE THREAD

**Issue by jmebartlett** [designdetails/designdetails#616]
Frustrations with existing products got me into design. As you guys have new Macs, perhaps now's a good time to share your frustrations with Mac OS, and ideate on ways to mitigate. For example, I'd like to see an inbox for Airdrop. Currently everything airdroped, gets dropped into the downloads folder, and with no way to sort by sender etc.

Thanks!
James

**Comment by brianlovin** [comment]
Ranted about in this week's episode, thanks for the topic! https://designdetails.fm/episodes/dSCbtu24
