### ISSUE TITLE
Design system question: How many variants is too many variations?

### ISSUE THREAD

**Issue by bryanmanio** [designdetails/designdetails#619]
### Context

I'm currently working on a design system, focusing on a card component with a ton of optional fields.

![CleanShot 2021-12-21 at 14 46 39](https://user-images.githubusercontent.com/846112/147001711-5000f876-0243-437a-b2b9-3fd4801ca916.png)

Building out a card with this many variants is great for the end design system user since it shows the optional fields available in the CMS that powers the layout of this design in the iOS app.

But maintaining this card and its 128 variants seems like a pain in the ass for the future design system team.

![CleanShot 2021-12-21 at 14 49 07](https://user-images.githubusercontent.com/846112/147001888-b4724c80-a965-437e-bc74-3bad39733e94.png)

### My question

Based on your experience, is this method sustainable? Is forcing the user to hide/show layers a better option to reduce complexity? Should I break out the component into more subcomponents to create fewer variants, but which causes more clicking around?

Help!

**Comment by brianlovin** [comment]
Discussed in last week's episode! Let us know if you have any follow-on thoughts, hope it was helpful 😊 https://designdetails.fm/episodes/q0TC2bln

**Comment by branhillsdesign** [comment]
Was listening to this episode today and I happened to run across this tweet from last year that explains "slots" in a loom video. Could be a useful way to solve this problem, but communication may be required within the team.

Hope this helps, @bryanmanio 

https://twitter.com/disco_lu/status/1387406350733479939

**Comment by bryanmanio** [comment]
@branhillsdesign Whoa, I haven't seen this approach before. Thanks!
