### ISSUE TITLE
What's the deal with Snapchat?

### ISSUE THREAD

**Issue by ZachShea** [designdetails/designdetails#624]
I've always wondered how Snapchat was able to get away with a design that broke so many conventions, particularly in the way you navigate the app. Overtime, they seem to have been returning to a normal nav pattern, especially now with the new tab bar design.

What do you think of the app's design and evolution, and do you know of any other apps that break the rules and still find success?

**Comment by brianlovin** [comment]
We poked at this in today's episode, thanks for the prompt Zach! https://designdetails.fm/episodes/LUrG39xL
