### ISSUE TITLE
Tools and approach for enterprise-scale icon systems

### ISSUE THREAD

**Issue by shanberg** [designdetails/designdetails#627]
How would you approach building a new icon system of the scale and depth of SF Symbols?

What tools would you use to create and manage the glyphs, repeated elements, and variants?

**Comment by brianlovin** [comment]
We discussed this in last week's Sidebar (on [Patreon](https://patreon.com/designdetails)) — thanks for asking 😊 https://designdetails.fm/episodes/e_mvcgAH
