### ISSUE TITLE
What makes a good manager?

### ISSUE THREAD

**Issue by Mannnny** [designdetails/designdetails#631]
Hi guys, 

Following up from last week’s episode: 

Speaking of being a team lead or manager, what do you think are the core skills a manager should have? Also when do you know you’re ready to be a team lead or manager? Do you have to be an great IC to be a manager? I personally don’t think so, they’re very different roles and requires different skills.

Thanks!

**Comment by brianlovin** [comment]
We started talking about this in today's episode, and will spend a bit more time here next week (it's a great question!) https://designdetails.fm/episodes/LUrG39xL
