### ISSUE TITLE
System for keeping latest design mockups?

### ISSUE THREAD

**Issue by emilyjikim** [designdetails/designdetails#632]
Hi! I'm curious how other teams maintain their "latest design" mockups for designs that have been shipped. 

I'm in a small team of two designers, and right now we have a figma file where we make a new page for each new version of the app that's been shipped. We throw in _every single page_ of the app for each version that was released (even if changes were only made on 2-3 pages). 

We landed on this method because we wanted to keep a clear picture of what the released designs are when we're starting a new project. However it is getting a little annoying  to maintain (and also the file too heavy). Do other teams do this too? I'm sure every team has a different method, but if you have any good tips on how you maintain shipped designs, I'd love to know! Thanks!

Emily

**Comment by brianlovin** [comment]
We discussed this in today's episode — let me know if anything else comes to mind after listening! https://designdetails.fm/episodes/LUrG39xL
