### ISSUE TITLE
Bulk-detach component Follow up

### ISSUE THREAD

**Issue by nachosdesign** [designdetails/designdetails#641]
Hello lovely people,

In the latest episode, you talked about the bulk-detach functionality in Figma <- This is super fast, but I've run into issues before since it only detaches components and not styles, so if the styles later change, any old designs run the risk of being updated.

I've been using a plugin called [Seek and Destroy](https://www.figma.com/community/plugin/1002696113544894116/Seek-and-Destroy) (awesome name) that will detach all components and styles of a selection. This truly freezes designs in time.

Highlight recommended!

**Comment by brianlovin** [comment]
Smart! Will add this to follow up for next week.
