### ISSUE TITLE
Making a case for icons

### ISSUE THREAD

**Issue by PriscillaThen** [designdetails/designdetails#646]
The Lead Developer at my work requested to remove some of the icons, because they slow down development time when having to wait for one to be created, grappling with SVGs, etc.  Unfortunately, he is right as they are time-consuming to make (especially good ones) and since I'm the only UX/UI designer in the company, it slows me down and I become the bottleneck. 

That said, I feel that icons give character, polish and professionalism to an otherwise extremely utilitarian UI. Icons can also be functional in that they help make certain elements stand out from an otherwise huge sea of text, but they are still seen as "fluff". I've asked for another designer to be hired, or request our graphic designer to create icons when he has time, but these suggestions didn't get any support. How would you make a case for icons when they are seen as mere decoration?

**Comment by brianlovin** [comment]
Discussed in this week's episode! https://designdetails.fm/episodes/7lfvlY4w
