### ISSUE TITLE
Sticking To Your Idea

### ISSUE THREAD

**Issue by Nocodecarlos** [designdetails/designdetails#650]
Hey there, Im new to the design field, three months into my UX role and I have a fear that I dont have strong enough opinions or knowledge to come up with a solution and push it forward all the way through. 

I think, my problem is that I am overly empathetic and always end up seeing the best in other peoples idea and going along with it but Im concerned I wont be getting far ahead if I cant stick by guts every now and then, or may get advantage of because Im a “yes man”. 

How do you build your “no” muscle without damaging relationships 

thanks all

**Comment by brianlovin** [comment]
Discussed in episode 434! https://designdetails.fm/episodes/93CwEe_9
