### ISSUE TITLE
When there is new feature in app, how do you guys make sure that you considered all the scenarios and designed all the screens which will be affected by this change?

### ISSUE THREAD

**Issue by Kriss045** [designdetails/designdetails#655]
I know this is such a beginner mistake and with experience I will become better at this but all the designers(by all I meant 3) at my workplace keep making this mistake. I am wondering is there any process to follow which can solve this problem so we don't have to revisit and redesign certain things again and again. Keep in mind that we are startup so most of the people are still in early phase of their career(from designers to Project managers) and there is not any standard process we follow.

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/wWCM6QBx
