### ISSUE TITLE
Evolving design crits as your team grows

### ISSUE THREAD

**Issue by ryanstonedesign** [designdetails/designdetails#660]
Hey friends! My UX team has grown immensely in past year, to 30+ members. We have weekly 1-hour design crits where anyone can share work & receive feedback. This has been helpful in leveling up presentation and feedback-giving skills, as well as unblocking team members and maintaining alignment. 

This has become challenging at scale though. Any tips to make crits more useful for larger teams, or are we destined to break apart?

**Comment by brianlovin** [comment]
Discussed on this week's episode! https://designdetails.fm/episodes/IDnXOlbZ
