### ISSUE TITLE
Interested in doing a podcast at Design Details

### ISSUE THREAD

**Issue by SonalShintre** [designdetails/designdetails#661]
Hey there!
I am Sonal Gadre-Shintre, a graphic designer & founder of www.kalakatta.studio.
I would be interested in doing a podcast at Design Details. Could you please let me know what is the procedure to submit the profile or submit the subject or do you suggest a subject?
Let me know. Thank you!
- Sonal

**Comment by brianlovin** [comment]
We aren't taking guest speaking requests right now 😊
