### ISSUE TITLE
How do you establish a recurring design critique session?

### ISSUE THREAD

**Issue by amiechen** [designdetails/designdetails#666]
Hi Brian & Marshall,

Long time listener here. Love the show and appreciate all the works go into it! 

I have a question: I'm part of a design team that has lots of talented designers and everyone is supportive, humble, and doing great work. But no one seems to want to sign up for weekly design critiques (but rather like sharing WIP in slack) and every time my manager encourages she would hear all kinds of excuses. Curious how does your team establish a recurring design critique sessions? Is it mendatory? or does everyone just love to share? What's the process of signing up one?

Thank you,
Amie

**Comment by brianlovin** [comment]
Discussed on today's episode, thanks for asking the question! https://designdetails.fm/episodes/5q57lh6O
