### ISSUE TITLE
Job board navigation button not working (designdetails.fm)

### ISSUE THREAD

**Issue by SushovanD** [designdetails/designdetails#670]
Reporting a bug in the Design Details website navigation bar:

**Expected behaviour:**
Clicking on the Job board nav button should take me to https://designdetails.pallet.com/jobs on a new tab. 🏁 

**Current behaviour:**
Clicking on the said nav button takes me... nowhere. 😞 
Right-click, Open in new tab works fine.

https://user-images.githubusercontent.com/7003069/168345792-44ad4339-eb8d-4bab-96ab-dc8a08a50907.mov

Most likely Culprit:

`		<Link href="/jobs">
			<a>
				<NavItem>
					Job Board <LinkExternal />
				</NavItem>
			</a>
		</Link>`

(PS - Feels weird to use Github issues on the Design details repo to report issues, instead of suggesting topics 😆 )

**Comment by brianlovin** [comment]
This should be fixed! Thank you 🙏
