### ISSUE TITLE
How do you explain what you do?

### ISSUE THREAD

**Issue by EricHaftMaxwell** [designdetails/designdetails#675]
I feel like when the general public asks "what do you do?" it's a short conversation.  How do you both explain what you do to the "layman" and keep it interesting and relatable?  Thanks!

**Comment by brianlovin** [comment]
Discussed in the back-half of last week's episode! https://designdetails.fm/

**Comment by EricHaftMaxwell** [comment]
Good stuff, thanks for discussing!
