### ISSUE TITLE
Advice for junior designers

### ISSUE THREAD

**Issue by yurongdnc12** [designdetails/designdetails#680]
Hello there! I know that there has been similar content shared on this topic, on how to become a senior designer or how to close the gap. My question is angled more from do you have any advice for junior designers and how to plot our growth more intentionally. What's your top few advice for intentional growth for junior designers? i.e. should we try to work on a range of products in different industries in our "younger" days? 
I want to get good as a designer and not only become a senior designer just because "I have worked in a company long enough" (for example).

**Comment by brianlovin** [comment]
Discussed in last week's Sidebar! https://www.patreon.com/posts/68803298
