### ISSUE TITLE
Performance Review - How to write effective self reviews? 

### ISSUE THREAD

**Issue by gaurangalat** [designdetails/designdetails#683]
It's performance review season again! Would love to hear from you two about strategies, frameworks and tips you typically use while writing self-reviews, especially when you are aiming to level up to the next level as a product designer. Beyond using metrics, how can I effectively present the overall impact of my work as an IC?

**Comment by brianlovin** [comment]
Discussed in today's episode! https://designdetails.fm/episodes/e2ho_2s9
