### ISSUE TITLE
What's the purpose of button sizes?

### ISSUE THREAD

**Issue by JoeyPearlman** [designdetails/designdetails#704]
Button sizes are something I see in every design system, but I've never seen documentation beyond something like "Our design system has 5 button sizes, from extra-small to extra-large"

What's the purpose of button sizes? 

Are they meant to be used for hierarchy, so that big single actions like "Sign up" are larger and more emphasized than smaller things, like a button row with multiple options like "edit, next, previous, delete"? 

Or are they meant to be used for different breakpoints so that you can swap in larger buttons for touch screens and smaller buttons for clickable elements? 

How do you consider button size options when adding a button to your design, and when do you decide to veer from the default size and instead use a Small button or Large button? When do you use the extremes of the scale like Extra Small or Extra Large?

**Comment by brianlovin** [comment]
Discussed in today's ep! https://designdetails.fm/episodes/1Cz5Nxiq
